
print("Welcome to the Haiku Generator!")
print("Provide the first line of your haiku.")
x = str(raw_input())
print("Provide the second line to your haiku.")
y = str(raw_input())
print("Provide the third line to your haiku.")
z = str(raw_input())
print("What file would you like to write your haiku into.")
myFile = str(raw_input())
print("Done! To view your haiku, type 'cat' and the name of your file at the command line")
my_File = open((myFile), "a")
my_File.write( x + '\n' + y + '\n' + z + '\n')
my_File.close()
